### ISSUE TITLE
Transitions between videos?

### ISSUE THREAD

**Issue by j0hn** [glslio/glsl.io#89]
Is it possible to create transitions using `<video>` elements instead of `<img>`?

**Comment by gre** [comment]
Can you explain a bit more, I'm not understanding your question, I suspect you have used an HTML markup in your question? Github doesn't allow that and will replace blank ^^

Thanks

**Comment by j0hn** [comment]
huh, sorry, i updated the comment

**Comment by gre** [comment]
Technically yes it is possible.

So GLSL.io uses [glsl-transition](https://www.npmjs.com/package/glsl-transition) which is the minimal core library for running a GLSL Transition.

and with the use of [`gl-texture2d`](https://www.npmjs.com/package/gl-texture2d) you can create Texture from a `< video / >`.

If you want, you can give try, otherwise I will try to provide an "Example 3" in **glsl-transition**.

> As a side note:
Recently I've been working on [`diaporama`](https://github.com/gre/diaporama) which provides an higher level API to use GLSL Transitions specifically for making slideshows. However it **does not** support yet videos.

**Comment by gre** [comment]
**DEMO: http://greweb.me/glsl-transition/examples/3/**

code:
https://github.com/gre/glsl-transition/blob/master/examples/3/index.js


That's just one example. the 3 videos are looping and there is no pauses between the transitions.

Also you have to know that **< video />** is still not very stable and consistent across OS, Browsers, Platform (especially mobile). You may reach issues in term of support and load event. I used a workaround to load the video via an Ajax request first.

**Comment by j0hn** [comment]
that's awesome, thanks!
